"""Hinglish, Marathi (Devanagari + Roman) and Hindi training phrases per category.

Used by train.py together with the English CORPUS. Keep these DIFFERENT from the
sentences in test_multilingual.py and test_language_rootcause.py, otherwise the
benchmarks stop measuring generalisation.
"""

MULTILINGUAL_CORPUS = {
    "fire": [
        "dukaan me aag lag gayi hai fire brigade bhejo",
        "building ke upar wale flat se aag ki lapte dikh rahi hai",
        "kachre ke dher me aag lagi hai dhua phail raha hai",
        "इमारतीच्या तिसऱ्या मजल्यावर आग लागली आहे",
        "गोदामाला आग लागली असून धूर पसरला आहे",
        "बिल्डिंग में आग लगी है लोग फंसे हुए हैं",
        "गाड़ी में अचानक आग लग गई",
        "dukanala aag lagli aahe lavkar ya",
    ],
    "gas": [
        "ghar me cylinder se gas leak ho rahi hai",
        "gali me pipeline se gas ki badboo aa rahi hai",
        "hotel ke kitchen me gas leak hai sab dar gaye hain",
        "स्वयंपाकघरात सिलेंडरमधून गॅस गळती होत आहे",
        "सोसायटीच्या पाईपलाईनमधून गॅसचा वास येतोय",
        "सिलेंडर लीक हो रहा है गैस की गंध आ रही है",
        "ज़मीन के नीचे की गैस लाइन फट गई है",
        "gharat gas cha vaas yetoy cylinder leak aahe",
    ],
    "electric": [
        "subah se bijli nahi hai poora area andhere me hai",
        "street light kharab hai raat ko andhera rehta hai",
        "transformer se chingariyan nikal rahi hain",
        "बिजली का तार सड़क पर गिरा हुआ है करंट का खतरा",
        "आमच्या भागात सकाळपासून वीज नाही",
        "रस्त्यावरचे दिवे बंद आहेत रात्री अंधार असतो",
        "डीपी मधून ठिणग्या उडत आहेत",
        "kal pasun vij nahi aahe sagla andhar",
    ],
    "water": [
        "do din se nal me paani nahi aa raha",
        "paani ki supply bahut kam pressure me aati hai",
        "nal se ganda aur badboodar paani aa raha hai",
        "आमच्या इमारतीला पिण्याचे पाणी मिळत नाही",
        "पाण्याची पाईपलाईन फुटली आहे पाणी वाया जात आहे",
        "नल में पानी नहीं आ रहा टैंकर भेजो",
        "पीने के पानी में कीड़े आ रहे हैं",
        "nalala pani yet nahi tanker pathva",
    ],
    "drainage": [
        "gutar ka paani ghar me ghus raha hai",
        "nali choke ho gayi hai ganda paani sadak pe beh raha hai",
        "baarish me har baar is gali me paani bhar jata hai",
        "पावसामुळे गल्लीत गुडघाभर पाणी साचले आहे",
        "ड्रेनेज लाईन फुटून घाण पाणी वाहत आहे",
        "नाला ओवरफ्लो हो रहा है गंदा पानी घरों में",
        "मैनहोल से सीवर का पानी बाहर निकल रहा है",
        "gutar tumbale aahe ghaan pani rastyavar",
    ],
    "sanitation": [
        "kachra gaadi hafte bhar se nahi aayi",
        "gali me kuda pada hai koi uthata nahi",
        "kooda daan bhar gaya hai chaaron taraf gandagi",
        "रस्त्याच्या कडेला कचऱ्याचा ढीग साचला आहे",
        "कचरा उचलला जात नाही दुर्गंधी पसरली आहे",
        "सड़क किनारे कूड़े का ढेर लगा है बदबू आ रही है",
        "सफाई वाला कई दिन से नहीं आया",
        "ghantagadi yet nahi kachra sadat aahe",
    ],
    "road": [
        "sadak pe bahut gaddhe hain gaadi chalana mushkil",
        "naya road ek mahine me hi toot gaya",
        "road ki khudai karke chhod diya hai",
        "रस्त्यावर मोठा खड्डा पडला आहे अपघात होऊ शकतो",
        "डांबरीकरण उखडले आहे रस्ता खराब झाला",
        "सड़क टूटी हुई है गड्ढों में पानी भरा है",
        "पुल की सड़क पर बड़ी दरारें आ गई हैं",
        "rastyat khup khadde aahet bike ghasarte",
    ],
    "traffic": [
        "signal kaam nahi kar raha chowk pe jam hai",
        "log galat jagah gaadi park karte hain rasta band",
        "school ke time bahut traffic jam hota hai",
        "सिग्नल बंद असल्याने चौकात वाहतूक कोंडी",
        "रस्त्यावर बेशिस्त पार्किंगमुळे गाड्या अडकतात",
        "चौराहे पर ट्रैफिक सिग्नल खराब है",
        "गलत पार्किंग से एंबुलेंस फंस गई",
        "chowkat signal band aahe traffic jam",
    ],
    "noise": [
        "raat ko der tak dj baj raha hai",
        "padosi ka loudspeaker bahut tez hai",
        "construction ka shor raat bhar chalta hai",
        "रात्री उशिरापर्यंत डीजेचा आवाज सुरू असतो",
        "मंदिराच्या भोंग्याचा खूप मोठा आवाज",
        "रात में तेज़ आवाज़ में लाउडस्पीकर बज रहा है",
        "पड़ोस में देर रात तक पार्टी का शोर",
        "ratri dj cha khup aawaz aahe zop yet nahi",
    ],
    "housing": [
        "building ki deewar me badi daraar aa gayi hai",
        "chhat ka plaster gir raha hai bacche dar gaye",
        "purani imarat kabhi bhi gir sakti hai",
        "इमारतीच्या भिंतीला तडे गेले आहेत",
        "छताचे प्लास्टर कोसळत आहे धोकादायक",
        "पुरानी इमारत जर्जर हालत में है गिर सकती है",
        "दीवार में दरार आ गई है छत से पानी टपकता है",
        "building chi bhint padnyachya avasthet aahe",
    ],
    "environment": [
        "aandhi me bada ped gir gaya rasta band hai",
        "park me ghaas bahut badh gayi hai koi dekhta nahi",
        "sukha ped kabhi bhi gir sakta hai",
        "वादळामुळे मोठे झाड कोसळले आहे",
        "बागेत झाडांच्या फांद्या तुटून पडल्या आहेत",
        "पार्क में पेड़ की डाली टूटकर लटक रही है",
        "बगीचे की देखभाल नहीं हो रही",
        "zhaad padla aahe rasta band zala",
    ],
    "pollution": [
        "factory se kala dhua nikal raha hai saans lena mushkil",
        "nadi me chemical waala paani chhoda ja raha hai",
        "construction ki dhool se hawa kharab hai",
        "कारखान्यातून काळा धूर निघत आहे",
        "हवेत खूप धूळ आणि प्रदूषण आहे",
        "फैक्ट्री का ज़हरीला धुआं बस्ती में फैल रहा है",
        "नदी में रसायन मिला पानी छोड़ा जा रहा है",
        "karkhanyatun vishari dhur yetoy",
    ],
    "animals": [
        "gali me awara kutte logo ko kaat rahe hain",
        "sadak pe gaay bhains baithi rehti hai",
        "bandar ghar me ghus kar saman le jaate hain",
        "भटक्या कुत्र्यांनी मुलाला चावा घेतला",
        "रस्त्यावर जनावरे फिरत असतात",
        "आवारा कुत्ते बच्चों के पीछे भागते हैं",
        "घर के आंगन में सांप निकला है",
        "bhatke kutre khup aahet raatri bhuktat",
    ],
    "public_transport": [
        "bus time pe nahi aati roz late hoti hai",
        "auto wale meter se nahi chalte zyada kiraya maangte",
        "bus stop ka shelter toota hua hai",
        "बस वेळेवर येत नाही प्रवाशांचे हाल",
        "रिक्षावाले जास्त भाडे मागतात",
        "बस स्टॉप पर बस रुकती नहीं है",
        "मेट्रो स्टेशन की लिफ्ट बंद पड़ी है",
        "bus thamba todla aahe bus vel var yet nahi",
    ],
    "encroachment": [
        "footpath pe thele walon ne kabza kar liya hai",
        "sarkari zameen par avaidh nirmaan ho raha hai",
        "dukaan ka saaman sadak tak rakha hai",
        "पदपथावर फेरीवाल्यांचे अतिक्रमण आहे",
        "मोकळ्या जागेवर अनधिकृत बांधकाम सुरू आहे",
        "फुटपाथ पर दुकानदारों ने कब्ज़ा कर लिया है",
        "सरकारी ज़मीन पर अवैध झोपड़ियां बना ली गई हैं",
        "footpath var feriwale basle aahet chalayla jaga nahi",
    ],
    "public_safety": [
        "raat ko gali me chori ki ghatnaye badh gayi hain",
        "bike wale chain chheen kar bhaag gaye",
        "nukkad pe sharabi log ladkiyon ko chhedte hain",
        "रात्री गल्लीत गुंडांचा वावर असतो असुरक्षित वाटते",
        "आमच्या सोसायटीत चोरी झाली आहे",
        "मोहल्ले में रात को लूटपाट हो रही है",
        "पार्क में नशेड़ी लोग बैठे रहते हैं",
        "rasta var mulinchi chhed kadhli jaate police nahi",
    ],
    "health": [
        "area me bahut machhar hain dengue ke case aa rahe",
        "sarkari hospital me doctor nahi milte",
        "gali me fogging nahi hui bukhar phail raha hai",
        "डासांमुळे परिसरात डेंग्यूचे रुग्ण वाढले",
        "आरोग्य केंद्रात औषधे मिळत नाहीत",
        "इलाके में मलेरिया के मरीज़ बढ़ गए हैं",
        "अस्पताल में एम्बुलेंस समय पर नहीं आती",
        "dasanchi favarni kara dengue vadhla aahe",
    ],
}
